# This file was generated by GoReleaser. DO NOT EDIT.
cask "byre" do
  version "1.5.0"

  on_macos do
    on_intel do
      sha256 "c744474c2fb4ce0310a4e7568383ebb5f60cfa1ae7264496f932630c8b79daeb"
      url "https://github.com/pjlsergeant/byre/releases/download/v#{version}/byre_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e4ac9da064045c660356b83aa5d05ef750d4161f3bcef25f87f05109a70e140c"
      url "https://github.com/pjlsergeant/byre/releases/download/v#{version}/byre_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "de335d56e8631c49320dec0a2bcab6d2254fd7e414f269967fc53498dfd40987"
      url "https://github.com/pjlsergeant/byre/releases/download/v#{version}/byre_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "00160ca29e94693705b8f46c92afa1dc6922a63cddd133a75734c5e73b901378"
      url "https://github.com/pjlsergeant/byre/releases/download/v#{version}/byre_#{version}_linux_arm64.tar.gz"
    end
  end

  name "byre"
  desc "Run an AI coding agent in a throwaway, project-scoped container"
  homepage "https://pjlsergeant.github.io/byre/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "byre"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/byre"]
    end
  end

  # No zap stanza required

end
