# This file was generated by GoReleaser. DO NOT EDIT.
cask "byre" do
  version "1.7.0"

  on_macos do
    on_intel do
      sha256 "559adb8ee0ea6a51da1ff605830a062aa52b3a789bcd33c39990971ded4dd612"
      url "https://github.com/pjlsergeant/byre/releases/download/v#{version}/byre_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "769144322a2faca7587b8b3308bcd7ba50fdf164031add78b783946d50ea8b19"
      url "https://github.com/pjlsergeant/byre/releases/download/v#{version}/byre_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ad655e024052e17ff300108abf871f0aaa3f72d55e647a79b089a0272988a28c"
      url "https://github.com/pjlsergeant/byre/releases/download/v#{version}/byre_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ae92e7554a39c3dd7e64c7fa4c43687c12fd307f5bcaeb90198b90878cfeb029"
      url "https://github.com/pjlsergeant/byre/releases/download/v#{version}/byre_#{version}_linux_arm64.tar.gz"
    end
  end

  name "byre"
  desc "Run an AI coding agent in a throwaway, project-scoped container"
  homepage "https://pjlsergeant.github.io/byre/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "byre"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/byre"]
    end
  end

  # No zap stanza required

end
