# This file was generated by GoReleaser. DO NOT EDIT.
cask "byre" do
  version "1.9.0"

  on_macos do
    on_arm do
      sha256 "706e975fdb0d9f6ff237eed03acafd4baf87470822f9c23eab122c75c6c1da59"
      url "https://github.com/pjlsergeant/byre/releases/download/v#{version}/byre_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d7f178457c70467cfff7a72acc4a80350da609b5b2fded3c9ef9cad72ec06726"
      url "https://github.com/pjlsergeant/byre/releases/download/v#{version}/byre_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "dd6ed012da2dbabafc1eabfb7ee4383d1c62b4bf9765a2216168b54e8ad0b696"
      url "https://github.com/pjlsergeant/byre/releases/download/v#{version}/byre_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "dbfb4d995a81a91cac37e02282418fb87087b12af703b416032e9dabac584162"
      url "https://github.com/pjlsergeant/byre/releases/download/v#{version}/byre_#{version}_linux_amd64.tar.gz"
    end
  end

  name "byre"
  desc "Run an AI coding agent in a throwaway, project-scoped container"
  homepage "https://pjlsergeant.github.io/byre/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "byre"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/byre"]
    end
  end

  # No zap stanza required
end
